apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-kcmainmicro
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kcmainmicro
  template:
    metadata:
      labels:
        app: kcmainmicro
    spec:
      serviceAccountName: kc-service-account
      containers:
        - name: back-end
          image: 673380487826.dkr.ecr.eu-west-1.amazonaws.com/kcmainmicro:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080